# Generated by Django 3.2.4 on 2021-06-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
