# Generated by Django 3.2.4 on 2021-07-19 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_comment_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation',
            new_name='step1',
        ),
        migrations.AddField(
            model_name='recipe',
            name='step2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='step3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
