# Generated by Django 3.2.4 on 2021-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210621_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_wrapped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sliced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
