# Generated by Django 3.2.4 on 2021-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210624_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_card',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
