# Generated by Django 3.2.4 on 2021-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210606_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='web_for_6_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_six',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
