# Generated by Django 3.2.4 on 2021-06-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Forsix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('for6', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('for12', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('for24', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
