# Generated by Django 3.2.4 on 2021-06-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210611_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product_id',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='products.product'),
        ),
    ]
