# Generated by Django 3.2.4 on 2021-06-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210611_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='products.product'),
        ),
    ]
