# Generated by Django 3.2.4 on 2021-06-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_size_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsix',
            old_name='product_id',
            new_name='product',
        ),
    ]
