# Generated by Django 3.2.4 on 2021-07-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210709_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flavour',
            new_name='allergens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
    ]
